<template>
    <!--Override the default tag used for the page -->
    <!--
        The Head component is used to define the meta information for the page, such as the title.
        The Title component is used to set the title of the page.
        The title is dynamically generated by including the product's title in the template.
    -->
    <Head>
        <Title>Nuxt 3 | Merch - {{ product.title }}</Title>
    </Head>

    <!-- Render the ProductDetails component and pass the product data as a prop -->
    <div>
        <ProductDetails :product="product"/>
    </div>
</template>

<script setup>
    // Get the id parameter from the current route
    const {id} = useRoute().params
    
    // Construct the URI for the product API endpoint, including the id parameter
    const uri = 'https://fakestoreapi.com/products/' + id
    
    // Fetch the product data from the API using the useFetch composable
    // The key option is used to cache the data and prevent unnecessary API calls
    const { data: product } = await useFetch(uri, { key: id })

    if(!product.value) {  
        // If the product data is not available, redirect to the 404 page
        // Throw a 404 error using the createError function from the nuxt/app package.
        // The statusCode and statusMessage properties are used to specify the error status and message.
        // The fatal propertyindicate that the error is fatal and should stop the server execution. (catch brower error(500))
        throw createError({ statusCode: 404, statusMessage: 'Product not found', fatal: true })
      }
    
    // Define the page metadata, specifying the layout to use for this page
    definePageMeta({
        layout: 'products'
    })
</script>

<style scoped>

</style>